function swcolor(){var e=document.querySelector("html.tui");"dark"==e.getAttribute("data-theme")?(e.removeAttribute("data-theme"),Cookies.remove("moon")):(e.setAttribute("data-theme","dark"),Cookies.set("moon",1))}
function makesafeid(e){return e.trim().replace(/^(\W+\d+)|^(\d+\W+)|^\d+|^\W+/g,"")}
function onlyUnique(e,n,r){return r.indexOf(e)===n}
function uniquesort(e){return e.sort((e,n)=>e.localeCompare(n)),e.filter(onlyUnique)}
function safename(e){return e.replace(" ","_").replace(/\W/g,"")}

function qdownload(t,e){
	r=document.createElement("a"),a=Date.now(),o=new Blob([t],{type:"text/plain"});
	r.href=URL.createObjectURL(o),r.download=a+"-"+e,r.click(),URL.revokeObjectURL(r.href)
}

function tp_downloadbak(){var e=new ta_jsfunc().ls_jsbak();let t=document.createElement("a"),r=Date.now(),a=new Blob([e],{type:"text/plain"});t.href=URL.createObjectURL(a),t.download=r+"-json-var.js",t.click(),URL.revokeObjectURL(t.href)}
function tp_switch(e){if(document.querySelectorAll("button.active").forEach(function(e){e.classList.remove("active")}),"string"!=typeof e){var t=e.getAttribute("data-page");e.classList.add("active")}else{var t=e;(document.querySelector("button[data-page='"+t+"']")||document.querySelector("button[data-page='info']")).classList.add("active")}switch(document.querySelectorAll("main").forEach(function(e){e.className="hide"}),document.querySelector("main#"+t).className="show",t){case"leads":seqpage();break;case"crafts":craftslist();break;default:document.getElementById("landing").innerHTML="<div><h1>Prompimix</h1><p>You see this pages, because this is the first time we notice you are using <b>Prompimix</b>. Your localstorage is empty, and we need to initially it. Please hit the Load button to doit, if you miss this step, you latter can doit at JSON Page.</p><p class='msg'><small>Fill your localstorage.</small> <button class='green' onclick='tp_reset(\"json\")'>Load</button></p></div></div>"}Cookies.set("last_page",t),feather.replace()}
function tp_scopeflush(){Cookies.remove("scope"),document.querySelector("#ped nav .scope").innerHTML=""}
function tp_addprompt(e){var t=["data-prefix","data-suffix"],r={};if("new"!==e){var a=e.closest("li").className,o=e.closest("li").querySelector("a").innerText.toLowerCase(),l=Array.from(document.querySelector(".data #data #"+a+" div.list").children),i=[];Array.from(l).forEach(function(e){i.push(e.innerText)}),t.forEach(function(e){r[e]=document.getElementById(safename(a)).getAttribute(e)})}else{var a="new",o="",i=[];t.forEach(function(e){r[e]=""})}document.querySelector("#prompts div.data").innerHTML=document.getElementById("ddform").innerHTML,document.querySelector("#prompts .ddform textarea").classList.add(a),document.querySelector("#prompts .ddform textarea").value=i.toString()||"",document.querySelector("#prompts .ddform .msg button").setAttribute("onclick","tp_newp('"+a+"')"),document.querySelector("#prompts .ddform input[name='name']").value=makesafeid(o),t.forEach(function(e){document.querySelector("#prompts .ddform input[name='"+e+"']").value=r[e]})}
function tp_newp(e){let t=new ta_jsfunc;var r=tp_trim(document.querySelector(".data .ddform textarea."+e).value);if("new"==e){var a=(e=makesafeid(document.querySelector(".data .ddform input[name='name']").value)).replace("_"," ").toLowerCase();console.log("update: "+a)}else var a=(e=makesafeid(document.querySelector(".data .ddform input[name='name']").value)).replace("_"," ").toLowerCase();var o=t.ls_get("prompts"),l=t.ls_get("spaces");if(void 0===l[a]&&(l[a]={}),void 0!==r&&r.length>1){var i=(r=(r=r.replace(/\n|\r/g,",")).replace(/, | ,/g,",")).split(",");i=uniquesort(i),e=document.querySelector(".data .ddform input[name='name']").value.trim(),o[a]=JSON.stringify(i),["data-prefix","data-suffix"].forEach(function(e){var t=document.querySelector(".data .ddform input[name='"+e+"']").value.trim();t=t.replace('"',""),l[a][e]=t}),console.log("update: "+a)}else console.log("delete: "+a),delete o[a],delete l[a];t.ls_save("spaces",JSON.stringify(l)),t.ls_save("prompts",JSON.stringify(o)),workspaces()}
function tp_arcopy(e){var t=e.closest("div.note").querySelector(".txt");console.log(t),t.select(),document.execCommand("copy")}
function tp_sample(){let e=new ta_jsfunc;var t,r=e.ls_get("prompts");rgp=void 0===(rgp=JSON.parse(e.ls_get("leads")[Cookies.get("template")||"default"]))?template_default:rgp.toString().split(",");var a="",o="";rgp.forEach(function(e){if("["==(e=e.replace("  "," ").trim()).substr(0,1))var t=e.replace(/\]/g," ").replace(/\[/g,"");else if(void 0!==r[e]){var l=JSON.parse(r[e]),t=l[Math.floor(Math.random()*l.length)],i=document.getElementById(safename(e)).getAttribute("data-prefix")||"",c=document.getElementById(safename(e)).getAttribute("data-suffix")||"";if(o!==e)var t=i+" "+t+" "+c;else var t=t+" "+c}a=""==a.trim()?t:o!==e?a+", "+t:a+document.getElementById("mixer").value+t,o=e}),document.querySelector("#ped textarea").value=tp_trim(a),tp_cookies(document.querySelector("#ped textarea")),button_notice(document.querySelector('button[title="Surprise me!"]'))}
function tp_jsonDownload(e){let t=JSON.stringify(new ta_jsfunc().ls_get(e)),r=document.createElement("a"),a=Date.now(),o=new Blob([t],{type:"text/plain"});r.href=URL.createObjectURL(o),r.download=a+"-"+e+".json",r.click(),URL.revokeObjectURL(r.href)}
function tp_clear(e){document.querySelector(e).value="",Cookies.remove("prompt"),tp_scopeflush()}
function tp_reset(e){!0==confirm("Are your sure?")&&("blank"===e?exec_workspace("blank"):exec_workspace("json"))}
function tp_cookies(e){var t=e.getAttribute("name");Cookies.set(t,e.value.trim())}
function tp_copytxt(e){document.querySelector(e).select(),document.execCommand("copy")}
function tp_saveit(e){var t=document.querySelector(e).value;let r=new ta_jsfunc,a=r.ls_get("crafts");console.log(a),void 0===a&&(a=[]),a.push(t.trim()),r.ls_save("crafts",JSON.stringify(a)),button_notice(document.getElementById("clipit"))}
function tp_filter(){var e=document.querySelectorAll("#data .topic span"),t=document.querySelector("#data input.filter").value.toLowerCase(),r=document.getElementById("toc"),a=document.getElementById("data");t.length<3?(r.classList.remove("filter"),a.classList.remove("filter"),document.querySelectorAll("#toc li").forEach(function(e){e.removeAttribute("found")}),document.querySelectorAll("#data div.topic").forEach(function(e){e.removeAttribute("found")}),e.forEach(function(e){e.classList.remove("found")})):(r.classList.remove("filter"),a.classList.remove("filter"),document.querySelectorAll("#toc li").forEach(function(e){e.removeAttribute("found")}),document.querySelectorAll("#data div.topic").forEach(function(e){e.removeAttribute("found")}),r.classList.add("filter"),a.classList.add("filter"),e.forEach(function(e){if(e.classList.remove("found"),e.innerText.toLowerCase().includes(t.toLowerCase())){e.classList.add("found");var r=e.closest("div.topic").querySelector("h4").getAttribute("href");document.querySelector("#toc li."+r).setAttribute("found",1),e.closest("div.topic").setAttribute("found",1)}}),document.querySelectorAll("#toc li").forEach(function(e){e.className.includes(t.toLowerCase())&&e.setAttribute("found",1)}),document.querySelectorAll("#data div.topic").forEach(function(e){e.id.includes(t.toLowerCase())&&e.setAttribute("found",1)}))}
function tp_leadsSelect(e){let t=e.value;update_leads(t),Cookies.set("template",t)}
function tp_addlead(){var e=prompt("Enter the new name:");if(e){let t=new ta_jsfunc;var l=t.ls_get("leads");l[e]="",t.ls_save("leads",JSON.stringify(l)),update_leads(e)}}
function tp_leadsave(e){let t=new ta_jsfunc;var l=t.ls_get("leads");let a=document.getElementById("lead_view"),s=a.getAttribute("data-lead");""==a.value?delete l[s]:(txt=a.value.replace("[","[").replace("]","]").replace(", ",",").replace(" ,",","),l[s]=JSON.stringify(txt.split(","))),t.ls_save("leads",JSON.stringify(l)),e&&button_notice(document.getElementById("lead_save_button"))}

function workspaces(){let e=new ta_jsfunc,t=new ta_lscookie;var a=e.ls_get("prompts"),r=e.ls_get("spaces"),i={};document.querySelector("#prompts .data").innerHTML="";var l=t.get("scope");void 0!==l&&(document.querySelector("#ped nav .scope").innerHTML=l.replace("_"," "));var n=document.createElement("div");n.id="data";var c=document.createElement("div");c.id="toc";var p=document.createElement("ul");p.innerHTML="<li class='new'><span>New</span><button onclick='tp_addprompt(\"new\")'><i data-feather='edit'></i></button></li>",n.innerHTML="<div id='filter'><div class='filter'><input onclick='this.value=\"\";tp_filter()' autocomplete='off' type='text' class='filter' onkeyup='tp_filter()' placeholder='Filters with at least 3 character...'><i data-feather='filter'></i></div></div>";var s="";uniquesort(Object.keys(a)).forEach(function(e,t){var l=document.createElement("div");l.id=safename(e),void 0!==r[e]&&(void 0!==r[e]["data-prefix"]&&l.setAttribute("data-prefix",r[e]["data-prefix"]),void 0!==r[e]["data-suffix"]&&l.setAttribute("data-suffix",r[e]["data-suffix"])),i[e]=[],l.classList.add("topic"),l.innerHTML="<div class='rel'><h4 href='"+safename(e)+"'>"+e+"</h4><a href='#filter'><i data-feather='arrow-up'></i></a></div>",s=s+"<li class='"+safename(e)+"'><a href='#"+safename(e)+"'>"+e+"</a><button onclick='tp_addprompt(this)'><i data-feather='edit'></i></button></li>";var c=uniquesort(JSON.parse(a[e])),p=document.createElement("div");p.className="list",c.forEach(function(t){var a=document.createElement("span");a.innerHTML=t,a.setAttribute("onclick","qcopy(this)"),p.append(a),i[e].push(t)}),i[e]=JSON.stringify(i[e]),l.append(p),n.append(l)}),p.innerHTML=p.innerHTML+s,c.append(p),document.querySelector("#prompts .data").append(c),document.querySelector("#prompts .data").append(n);var d=t.get("prompt");void 0!==d&&""!==d&&(document.querySelector("#ped textarea").value=d);var o=t.get("mixer");void 0!==o&&""!==o&&(document.querySelector("#mixer").value=o),feather.replace()}
function qcopy(e){if(e.classList.contains("dupe"))e.remove();else{var t="",a="",r=document.createElement("input");r.value="",r.setAttribute("type","hidden"),r.value=e.innerText;var i=e.closest("div.topic"),l=i.id,t=i.getAttribute("data-prefix")||"",a=i.getAttribute("data-suffix")||"",n=document.querySelector("#ped textarea").value,c=Cookies.get("scope");if(n.length<1&&tp_scopeflush(),c==l){var p=document.getElementById("mixer").value,s="";""!=a&&(n=n.replace(/\s+[^ ]+$/g,""));var d=p+r.value+" "+a}else{var s=", ",d=t+" "+r.value+" "+a;c=i.id,Cookies.set("scope",i.id),document.querySelector("#ped nav .scope").innerHTML=c.replace("_"," ")}cursorPosition=document.querySelector("#ped textarea").selectionStart;let o=n.substring(0,cursorPosition),u=n.substring(cursorPosition,n.length);n.length<1?document.querySelector("#ped textarea").value=d:cursorPosition>=n.length?document.querySelector("#ped textarea").value=n+s+d:document.querySelector("#ped textarea").value=o+d+u,tp_cookies(document.querySelector("#ped textarea"))}}
function craftslist(){var e=new ta_jsfunc().ls_get("crafts"),t="",a=0;void 0!==e&&void 0!==e.length&&e.forEach(function(e,r){t+="<div class='note'><button onclick='tp_arcopy(this)'><i data-feather='copy'></i></button><textarea class='txt'>",t+=e,t+="</textarea></div>",a+=1}),document.getElementById("collection").innerHTML=t}

function make_dropable(e,t,a={}){var n=document.createElement(t);return n.setAttribute("ondrop","drop(event)"),n.setAttribute("ondragover","allowDrop(event)"),a!=={}&&Object.keys(a).forEach(function(e){n.setAttribute(e,a[e])}),""!==e[0]&&e.forEach(function(e){var e=e.trim(),t=document.createElement("li");t.setAttribute("draggable","true"),t.setAttribute("ondragstart","dragstart(event)"),t.setAttribute("ondragend","dragend(event)"),t.id=safename(e+"_"+(Math.floor(900*Math.random())+100)),t.innerHTML=e,"["==e.substr(0,1)&&t.classList.add("static"),n.append(t)}),n}
function wrapper(e,t,a={}){var n=document.createElement(t);return a!=={}&&Object.keys(a).forEach(function(e){n.setAttribute(e,a[e])}),n.append(e),n}
function makeselection(e,t={},a=!1){var n=document.createElement("select");return t!=={}&&Object.keys(t).forEach(function(e){n.setAttribute(e,t[e])}),e.forEach(function(e){var t=document.createElement("option");t.value=e,t.innerText=e,e==a&&t.setAttribute("selected","selected"),n.append(t)}),n}
function rgp_process(e=[]){return e.forEach(function(e){"["==e.substr(0,1)?argp.push(e):Object.keys(prompts).includes(e)&&argp.push(e)}),agp}
function seqpage(e=!1){let t=new ta_jsfunc;var a=t.ls_get("prompts"),n=t.ls_get("leads"),l=Cookies.get("template")||"default",d=document.createElement("textarea");d.id="lead_view",d.setAttribute("data-lead",l),d.setAttribute("onchange","update_stack(false)");var r=document.createElement("nav"),s=document.createElement("div");s.innerHTML="<span class='note'><b>Note:</b> for static prompts: use [ and ], like [photo].</span><button id='lead_save_button' onclick='tp_leadsave(true)'><i data-feather='save'></i></button>";var i=document.createElement("div");i.innerHTML="<button onclick='tp_addlead()'><i data-feather='plus'></i></button><button title='Clear' onclick='tp_clear(\"#leads_view\")'><i data-feather='x-square'></i></button>";var c=makeselection(uniquesort(Object.keys(n)),{id:"leads_select",onchange:"tp_leadsSelect(this)"},l);i.prepend(wrapper(c,"span",{id:"lead_ctl"})),r.append(i),r.append(s);var p=document.createElement("div"),o=make_dropable(uniquesort(Object.keys(a)),"ul");p.className="tab-content",p.id="lgdnd",p.append(wrapper(o,"div",{id:"lstock",class:"stock dnd-area"}));var u=make_dropable([],"ul");p.append(wrapper(u,"div",{id:"lstack",class:"stack dnd-area"}));var v=document.getElementById("leads"),m=document.createElement("div");[r,d,p].forEach(function(e){m.append(e)}),v.innerHTML="",v.append(m),update_lta(d,l),update_stack(l)}
function update_lta(e,t){var a=new ta_jsfunc().ls_get("leads");null==e&&(e=document.getElementById("lead-view"));var n=a[t];void 0===n?e.value="":(e.value=JSON.parse(n).toString().replace(/\,/g,", ").replace(/  /g," "),e.setAttribute("data-lead",t))}
function update_stack(e=!1){e||(e=document.getElementById("lead_view").getAttribute("data-lead")||"default");let t=document.querySelector("#lstack");var a=document.getElementById("lead_view").value;t.innerHTML="";var n=document.createElement("h3");n.classname="lead_name",n.innerHTML=e;var l=document.createElement("button");l.setAttribute("onclick","json_pack(this)"),l.innerHTML="<i data-feather='download'></i><span>Json</span>";var d=document.createElement("div");d.className="flex packing",d.append(n),d.append(l);var r=make_dropable(a.split(","),"ul");t.append(d),t.append(r),feather.replace()}
function update_leads(e=!1){e?name=e:update_stack(name=document.getElementById("lead_view").getAttribute("data-lead")||"default");var t=new ta_jsfunc().ls_get("leads"),a=makeselection(uniquesort(Object.keys(t)),{id:"leads_select",onchange:"tp_leadsSelect(this)"},name);document.getElementById("lead_ctl").innerHTML="",document.getElementById("lead_ctl").append(a);let n="";""!=t[name]&&(n=JSON.parse(t[name])),e&&(document.getElementById("lead_view").value=n),document.getElementById("lead_view").setAttribute("data-lead",name),update_stack(name)}
function button_notice(e){e.classList.add("notice"),setTimeout(()=>{e.classList.remove("notice")},"1100")}

function allowDrop(e){e.preventDefault(),e.target.classList.add("drop-fx")}
function dragstart(e){e.dataTransfer.setData("text",e.target.id),e.dataTransfer.dropEffect="move",e.target.style.opacity="0.4"}
function dragend(e){e.target.style.opacity="1"}
function drop(e){e.preventDefault();var t=e.dataTransfer.getData("text"),r=e.target.closest("ul");document.querySelectorAll(".dnd-area .drop-fx").forEach(function(e){e.classList.remove("drop-fx")}),e.target==r?r.appendChild(document.getElementById(t)):(nli=e.toElement.closest("li"),r.insertBefore(document.getElementById(t),nli));var a=[];if((content=r.querySelectorAll("li")).forEach(function(e){a.push(e.innerText.trim())}),"lstock"==r.closest("div").id){var l=make_dropable(uniquesort(a),"ul");document.querySelector("#lstock").innerHTML="",document.querySelector("#lstock").append(l);var o=document.querySelector("#lstack ul").querySelectorAll("li"),a=[];o.forEach(function(e){a.push(e.innerText.trim())})}document.getElementById("lead_view").value=a.toString(),tp_leadsave()}

function handleuploadSubmit(){var e=document.getElementById("selectFiles").files;if(console.log(e),e.length<=0)return!1;var t=new FileReader;let l=new ta_jsfunc;var r=l.ls_get("prompts");t.onload=function(e){var t=__mergeJSON(r,JSON.parse(e.target.result));l.ls_save("prompts",JSON.stringify(t))},t.readAsText(e.item(0))}

function komadeal(e){var t=e.closest("div.ddform").querySelector("textarea[name=prompt_entries]");console.log(t);var s=t.value;t.value=s.replace(/\,/gi,"\n")}
function __mergeJSON(e,t){let s={...e};for(let r in t)Object.keys(e).includes(r)||console.log("+",r),t.hasOwnProperty(r)&&(s.hasOwnProperty(r)&&"object"==typeof s[r]&&"object"==typeof t[r]?s[r]=mergeJSON(s[r],t[r]):s[r]=t[r]);return s}
function findprompt(e){var t=[],s=[],r=new ta_jsfunc().ls_get("prompts");return Object.keys(r).forEach(function(n){n.includes(e)&&s.push(n),r[n].includes(e)&&t.push(n)}),{key:s,val:t}}
function packJSON(e){var t=new ta_jsfunc().ls_get("prompts"),s=findprompt(e),r={};r.prompts={},console.log(s),s.key.forEach(function(e){r.prompts[e]=t[e]}),qdownload(JSON.stringify(r),e+".json")}
function json_pack(e){var t=new ta_jsfunc().ls_get("prompts"),s=e.closest("div.stack"),r=s.querySelector("ul").querySelectorAll("li:not(.static)"),n=s.querySelector("h3").innerText,o=[],a={};r.forEach(function(e){o.push(e.innerText)}),console.log(o),o.forEach(function(e){a[e]=t[e]}),qdownload(JSON.stringify(a),n+".json")}
function pkremove(e){let t=new ta_jsfunc;var s=t.ls_get("prompts"),r=((e,{[e]:t,...s})=>s)(e,s);console.log(r),t.ls_save("prompts",JSON.stringify(r))}
function resetcookies(){["scope","last_page","template","moon"].forEach(function(e){Cookies.remove(e)}),console.log("Cookies reset...")}
function build_jsbak(){return new ta_jsfunc().ls_jsbak()}
function do_json_asvar_restore(){console.log(jsbak);let e=new ta_jsfunc;e.ls_reset(),e.ls_init({spaces:jsbak.spaces,prompts:jsbak.prompts,crafts:jsbak.crafts,leads:jsbak.leads},1)}
function load_json_asvar(){new ta_jsfunc().ls_check()?console.log("Already Populated"):(console.log("using: json-var.js"),loadScript("./data/json-var.js",do_json_asvar_restore))}
function loadScript(e,t){var s=document.head,r=document.createElement("script");r.type="text/javascript",r.src=e,r.onreadystatechange=t,r.onload=t,s.appendChild(r)}
function fixprompts(){let e=new ta_jsfunc;var t=e.ls_get("prompts");e.ls_get("spaces"),console.log("before",prompt);var s={};uniquesort(Object.keys(t)).forEach(function(e){np=uniquesort(JSON.parse(t[e])),s[e]=JSON.stringify(np),console.log(e,np.length+" items")}),console.log("after",s),e.ls_save("prompts",JSON.stringify(s))}
function fixspace(){let e=new ta_jsfunc;var t=e.ls_get("prompts"),s=e.ls_get("spaces");console.log(s);var r={};uniquesort(Object.keys(s)).forEach(function(e){Object.keys(t).includes(e)?r[e]=s[e]:console.log(e,"missing...")}),console.log(r),e.ls_save("spaces",JSON.stringify(r))}
function finddupe(){var e=new ta_jsfunc().ls_get("prompts"),t={},s=[];uniquesort(Object.keys(e)).forEach(function(r,n){var o=document.createElement("div");o.id=safename(r),t[r]=[],o.classList.add("topic"),o.innerHTML="<div class='rel'><h4 href='"+safename(r)+"'>"+r+"</h4><a href='#filter'><i data-feather='arrow-up'></i></a></div>";var a=uniquesort(JSON.parse(e[r])),i=document.createElement("div");i.className="list";var l=[];a.forEach(function(e){if(s.includes(e))l.push(e);else{var t=document.createElement("span");t.innerHTML=e,i.append(t),s.push(e)}}),document.querySelectorAll(".data #data div#"+safename(r)+" div.list span").forEach(function(e){l.includes(e.innerText)&&(e.classList.add("dupe"),console.log(e))})})}


